name: GuardianRFTB
version: ${project.version}
main: dev.mruniverse.guardianrftb.core.GuardianRFTB
authors: [ MrUniverse44, Sebastnchan ]
description: Run From the Beast Minigame but with new Features and Original systems.
website: play.servername.net
load: POSTWORLD
commands:
  gRFTB:
    description: Main command of the plugin
  GuardianRFTB:
    description: Main command of the plugin
  rftb:
    description: Main command of the plugin